CREATE TABLE FILE(
FILE_ID NUMBER PRIMARY KEY,
NAME NVARCHAR2(30) NOT NULL,
FORMAT NVARCHAR2(4),
SIZE NUMBER,
STORAGE_ID NUMBER,
CONSTRAINT SALESMAN_ID_FK FOREIGN KEY(STORAGE_ID) REFERENCES STORAGE (STORAGE_ID)
);

CREATE TABLE STORAGE(
STORAGE_ID NUMBER PRIMARY KEY,
FormatSupported NVARCHAR2(30),
StorageCountry NVARCHAR2(30),
StorageMaxSize NVARCHAR2(20)
);

CREATE TABLE HISTORY(
HISTORY_ID NUMBER PRIMARY KEY,
OperationType NVARCHAR2(14),
TimeProcessed NUMBER,
Status NVARCHAR2(12) NULL NULL
);

