CREATE TABLE PRODUCT (
ID NUMBER NOT NULL,
CONSTRAINT PRODUCT_ID PRIMARY KEY (ID),
NAME VARCHAR(100) NOT NULL,
DESCRIPTION CLOB,
PRICE NUMBER NOT NULL
);

CREATE TABLE TEST_SPEED (
ID NUMBER NOT NULL,
CONSTRAINT TEST_SPEED_ID PRIMARY KEY (ID),
SOME_STRING VARCHAR2(20) NOT NULL,
SOME_NUMBER NUMBER NOT NULL
);
